name: flutter_ui_marketplace
description: Flutter UI Marketplace - Browse and install beautiful UI packs
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  url_launcher: ^6.2.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  archive: ^4.0.7
  google_fonts: ^6.3.3
  flutter_highlight: ^0.7.0
  code_text_field: ^1.1.0
  csv: ^6.0.0
  provider: ^6.1.5+1
  desktop_drop: ^0.7.0
  cross_file: ^0.3.5+1
  mime: ^2.0.0
  image_picker: ^1.1.2
  analyzer: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
